/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginn;

/**
 *
 * @author USUARIO
 */
public class FromNotas extends javax.swing.JFrame {

    /**
     * Creates new form FromNotas
     */
    public FromNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInicio81 = new javax.swing.JButton();
        btnClases81 = new javax.swing.JButton();
        btnNotas81 = new javax.swing.JButton();
        jLabel325 = new javax.swing.JLabel();
        imagneinicio81 = new javax.swing.JLabel();
        jLabel326 = new javax.swing.JLabel();
        jLabel327 = new javax.swing.JLabel();
        jLabel328 = new javax.swing.JLabel();
        jPanel84 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel85 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel329 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel330 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 649));

        jPanel3.setBackground(new java.awt.Color(30, 90, 172));

        btnInicio81.setBackground(new java.awt.Color(4, 58, 121));
        btnInicio81.setText("INCIO");
        btnInicio81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio81ActionPerformed(evt);
            }
        });

        btnClases81.setBackground(new java.awt.Color(4, 58, 121));
        btnClases81.setText("CLASES");

        btnNotas81.setBackground(new java.awt.Color(4, 58, 121));
        btnNotas81.setText("NOTAS");

        jLabel325.setText("en aca nombre de la persona que ingrese");

        imagneinicio81.setText("imagne ");

        jLabel326.setText("jLabel2");

        jLabel327.setText("jLabel2");

        jLabel328.setText("en aca la iamgen de la persona");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagneinicio81, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(jLabel327, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel326, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClases81, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInicio81, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNotas81, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel328, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel325, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel328, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel325, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagneinicio81, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio81, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClases81, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel327, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotas81, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel326, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel84.setBackground(new java.awt.Color(51, 204, 255));

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel84Layout = new javax.swing.GroupLayout(jPanel84);
        jPanel84.setLayout(jPanel84Layout);
        jPanel84Layout.setHorizontalGroup(
            jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel84Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(9, 9, 9))
        );
        jPanel84Layout.setVerticalGroup(
            jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel84Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel329.setText("si aras todo con text are en aca pero ten een cuenta el combox con un botn que cambie o reinicie los datos ");

        jButton1.setText("ver nota");

        jLabel330.setText("escoje la clase ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel85Layout = new javax.swing.GroupLayout(jPanel85);
        jPanel85.setLayout(jPanel85Layout);
        jPanel85Layout.setHorizontalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel85Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel85Layout.createSequentialGroup()
                        .addGroup(jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel85Layout.createSequentialGroup()
                                .addComponent(jLabel329)
                                .addGap(0, 332, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel85Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel85Layout.createSequentialGroup()
                                .addComponent(jLabel330)
                                .addGap(246, 246, 246))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel85Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel85Layout.setVerticalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel85Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel330)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel329)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicio81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicio81ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClases;
    private javax.swing.JButton btnClases1;
    private javax.swing.JButton btnClases10;
    private javax.swing.JButton btnClases11;
    private javax.swing.JButton btnClases12;
    private javax.swing.JButton btnClases13;
    private javax.swing.JButton btnClases14;
    private javax.swing.JButton btnClases15;
    private javax.swing.JButton btnClases16;
    private javax.swing.JButton btnClases17;
    private javax.swing.JButton btnClases18;
    private javax.swing.JButton btnClases19;
    private javax.swing.JButton btnClases2;
    private javax.swing.JButton btnClases20;
    private javax.swing.JButton btnClases21;
    private javax.swing.JButton btnClases22;
    private javax.swing.JButton btnClases23;
    private javax.swing.JButton btnClases24;
    private javax.swing.JButton btnClases25;
    private javax.swing.JButton btnClases26;
    private javax.swing.JButton btnClases27;
    private javax.swing.JButton btnClases28;
    private javax.swing.JButton btnClases29;
    private javax.swing.JButton btnClases3;
    private javax.swing.JButton btnClases30;
    private javax.swing.JButton btnClases31;
    private javax.swing.JButton btnClases32;
    private javax.swing.JButton btnClases33;
    private javax.swing.JButton btnClases34;
    private javax.swing.JButton btnClases35;
    private javax.swing.JButton btnClases36;
    private javax.swing.JButton btnClases37;
    private javax.swing.JButton btnClases38;
    private javax.swing.JButton btnClases39;
    private javax.swing.JButton btnClases4;
    private javax.swing.JButton btnClases40;
    private javax.swing.JButton btnClases41;
    private javax.swing.JButton btnClases42;
    private javax.swing.JButton btnClases43;
    private javax.swing.JButton btnClases44;
    private javax.swing.JButton btnClases45;
    private javax.swing.JButton btnClases46;
    private javax.swing.JButton btnClases47;
    private javax.swing.JButton btnClases48;
    private javax.swing.JButton btnClases49;
    private javax.swing.JButton btnClases5;
    private javax.swing.JButton btnClases50;
    private javax.swing.JButton btnClases51;
    private javax.swing.JButton btnClases52;
    private javax.swing.JButton btnClases53;
    private javax.swing.JButton btnClases54;
    private javax.swing.JButton btnClases55;
    private javax.swing.JButton btnClases56;
    private javax.swing.JButton btnClases57;
    private javax.swing.JButton btnClases58;
    private javax.swing.JButton btnClases59;
    private javax.swing.JButton btnClases6;
    private javax.swing.JButton btnClases60;
    private javax.swing.JButton btnClases61;
    private javax.swing.JButton btnClases62;
    private javax.swing.JButton btnClases63;
    private javax.swing.JButton btnClases64;
    private javax.swing.JButton btnClases65;
    private javax.swing.JButton btnClases66;
    private javax.swing.JButton btnClases67;
    private javax.swing.JButton btnClases68;
    private javax.swing.JButton btnClases69;
    private javax.swing.JButton btnClases7;
    private javax.swing.JButton btnClases70;
    private javax.swing.JButton btnClases71;
    private javax.swing.JButton btnClases72;
    private javax.swing.JButton btnClases73;
    private javax.swing.JButton btnClases74;
    private javax.swing.JButton btnClases75;
    private javax.swing.JButton btnClases76;
    private javax.swing.JButton btnClases77;
    private javax.swing.JButton btnClases78;
    private javax.swing.JButton btnClases79;
    private javax.swing.JButton btnClases8;
    private javax.swing.JButton btnClases80;
    private javax.swing.JButton btnClases81;
    private javax.swing.JButton btnClases9;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInicio1;
    private javax.swing.JButton btnInicio10;
    private javax.swing.JButton btnInicio11;
    private javax.swing.JButton btnInicio12;
    private javax.swing.JButton btnInicio13;
    private javax.swing.JButton btnInicio14;
    private javax.swing.JButton btnInicio15;
    private javax.swing.JButton btnInicio16;
    private javax.swing.JButton btnInicio17;
    private javax.swing.JButton btnInicio18;
    private javax.swing.JButton btnInicio19;
    private javax.swing.JButton btnInicio2;
    private javax.swing.JButton btnInicio20;
    private javax.swing.JButton btnInicio21;
    private javax.swing.JButton btnInicio22;
    private javax.swing.JButton btnInicio23;
    private javax.swing.JButton btnInicio24;
    private javax.swing.JButton btnInicio25;
    private javax.swing.JButton btnInicio26;
    private javax.swing.JButton btnInicio27;
    private javax.swing.JButton btnInicio28;
    private javax.swing.JButton btnInicio29;
    private javax.swing.JButton btnInicio3;
    private javax.swing.JButton btnInicio30;
    private javax.swing.JButton btnInicio31;
    private javax.swing.JButton btnInicio32;
    private javax.swing.JButton btnInicio33;
    private javax.swing.JButton btnInicio34;
    private javax.swing.JButton btnInicio35;
    private javax.swing.JButton btnInicio36;
    private javax.swing.JButton btnInicio37;
    private javax.swing.JButton btnInicio38;
    private javax.swing.JButton btnInicio39;
    private javax.swing.JButton btnInicio4;
    private javax.swing.JButton btnInicio40;
    private javax.swing.JButton btnInicio41;
    private javax.swing.JButton btnInicio42;
    private javax.swing.JButton btnInicio43;
    private javax.swing.JButton btnInicio44;
    private javax.swing.JButton btnInicio45;
    private javax.swing.JButton btnInicio46;
    private javax.swing.JButton btnInicio47;
    private javax.swing.JButton btnInicio48;
    private javax.swing.JButton btnInicio49;
    private javax.swing.JButton btnInicio5;
    private javax.swing.JButton btnInicio50;
    private javax.swing.JButton btnInicio51;
    private javax.swing.JButton btnInicio52;
    private javax.swing.JButton btnInicio53;
    private javax.swing.JButton btnInicio54;
    private javax.swing.JButton btnInicio55;
    private javax.swing.JButton btnInicio56;
    private javax.swing.JButton btnInicio57;
    private javax.swing.JButton btnInicio58;
    private javax.swing.JButton btnInicio59;
    private javax.swing.JButton btnInicio6;
    private javax.swing.JButton btnInicio60;
    private javax.swing.JButton btnInicio61;
    private javax.swing.JButton btnInicio62;
    private javax.swing.JButton btnInicio63;
    private javax.swing.JButton btnInicio64;
    private javax.swing.JButton btnInicio65;
    private javax.swing.JButton btnInicio66;
    private javax.swing.JButton btnInicio67;
    private javax.swing.JButton btnInicio68;
    private javax.swing.JButton btnInicio69;
    private javax.swing.JButton btnInicio7;
    private javax.swing.JButton btnInicio70;
    private javax.swing.JButton btnInicio71;
    private javax.swing.JButton btnInicio72;
    private javax.swing.JButton btnInicio73;
    private javax.swing.JButton btnInicio74;
    private javax.swing.JButton btnInicio75;
    private javax.swing.JButton btnInicio76;
    private javax.swing.JButton btnInicio77;
    private javax.swing.JButton btnInicio78;
    private javax.swing.JButton btnInicio79;
    private javax.swing.JButton btnInicio8;
    private javax.swing.JButton btnInicio80;
    private javax.swing.JButton btnInicio81;
    private javax.swing.JButton btnInicio9;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnNotas1;
    private javax.swing.JButton btnNotas10;
    private javax.swing.JButton btnNotas11;
    private javax.swing.JButton btnNotas12;
    private javax.swing.JButton btnNotas13;
    private javax.swing.JButton btnNotas14;
    private javax.swing.JButton btnNotas15;
    private javax.swing.JButton btnNotas16;
    private javax.swing.JButton btnNotas17;
    private javax.swing.JButton btnNotas18;
    private javax.swing.JButton btnNotas19;
    private javax.swing.JButton btnNotas2;
    private javax.swing.JButton btnNotas20;
    private javax.swing.JButton btnNotas21;
    private javax.swing.JButton btnNotas22;
    private javax.swing.JButton btnNotas23;
    private javax.swing.JButton btnNotas24;
    private javax.swing.JButton btnNotas25;
    private javax.swing.JButton btnNotas26;
    private javax.swing.JButton btnNotas27;
    private javax.swing.JButton btnNotas28;
    private javax.swing.JButton btnNotas29;
    private javax.swing.JButton btnNotas3;
    private javax.swing.JButton btnNotas30;
    private javax.swing.JButton btnNotas31;
    private javax.swing.JButton btnNotas32;
    private javax.swing.JButton btnNotas33;
    private javax.swing.JButton btnNotas34;
    private javax.swing.JButton btnNotas35;
    private javax.swing.JButton btnNotas36;
    private javax.swing.JButton btnNotas37;
    private javax.swing.JButton btnNotas38;
    private javax.swing.JButton btnNotas39;
    private javax.swing.JButton btnNotas4;
    private javax.swing.JButton btnNotas40;
    private javax.swing.JButton btnNotas41;
    private javax.swing.JButton btnNotas42;
    private javax.swing.JButton btnNotas43;
    private javax.swing.JButton btnNotas44;
    private javax.swing.JButton btnNotas45;
    private javax.swing.JButton btnNotas46;
    private javax.swing.JButton btnNotas47;
    private javax.swing.JButton btnNotas48;
    private javax.swing.JButton btnNotas49;
    private javax.swing.JButton btnNotas5;
    private javax.swing.JButton btnNotas50;
    private javax.swing.JButton btnNotas51;
    private javax.swing.JButton btnNotas52;
    private javax.swing.JButton btnNotas53;
    private javax.swing.JButton btnNotas54;
    private javax.swing.JButton btnNotas55;
    private javax.swing.JButton btnNotas56;
    private javax.swing.JButton btnNotas57;
    private javax.swing.JButton btnNotas58;
    private javax.swing.JButton btnNotas59;
    private javax.swing.JButton btnNotas6;
    private javax.swing.JButton btnNotas60;
    private javax.swing.JButton btnNotas61;
    private javax.swing.JButton btnNotas62;
    private javax.swing.JButton btnNotas63;
    private javax.swing.JButton btnNotas64;
    private javax.swing.JButton btnNotas65;
    private javax.swing.JButton btnNotas66;
    private javax.swing.JButton btnNotas67;
    private javax.swing.JButton btnNotas68;
    private javax.swing.JButton btnNotas69;
    private javax.swing.JButton btnNotas7;
    private javax.swing.JButton btnNotas70;
    private javax.swing.JButton btnNotas71;
    private javax.swing.JButton btnNotas72;
    private javax.swing.JButton btnNotas73;
    private javax.swing.JButton btnNotas74;
    private javax.swing.JButton btnNotas75;
    private javax.swing.JButton btnNotas76;
    private javax.swing.JButton btnNotas77;
    private javax.swing.JButton btnNotas78;
    private javax.swing.JButton btnNotas79;
    private javax.swing.JButton btnNotas8;
    private javax.swing.JButton btnNotas80;
    private javax.swing.JButton btnNotas81;
    private javax.swing.JButton btnNotas9;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imagneinicio;
    private javax.swing.JLabel imagneinicio1;
    private javax.swing.JLabel imagneinicio10;
    private javax.swing.JLabel imagneinicio11;
    private javax.swing.JLabel imagneinicio12;
    private javax.swing.JLabel imagneinicio13;
    private javax.swing.JLabel imagneinicio14;
    private javax.swing.JLabel imagneinicio15;
    private javax.swing.JLabel imagneinicio16;
    private javax.swing.JLabel imagneinicio17;
    private javax.swing.JLabel imagneinicio18;
    private javax.swing.JLabel imagneinicio19;
    private javax.swing.JLabel imagneinicio2;
    private javax.swing.JLabel imagneinicio20;
    private javax.swing.JLabel imagneinicio21;
    private javax.swing.JLabel imagneinicio22;
    private javax.swing.JLabel imagneinicio23;
    private javax.swing.JLabel imagneinicio24;
    private javax.swing.JLabel imagneinicio25;
    private javax.swing.JLabel imagneinicio26;
    private javax.swing.JLabel imagneinicio27;
    private javax.swing.JLabel imagneinicio28;
    private javax.swing.JLabel imagneinicio29;
    private javax.swing.JLabel imagneinicio3;
    private javax.swing.JLabel imagneinicio30;
    private javax.swing.JLabel imagneinicio31;
    private javax.swing.JLabel imagneinicio32;
    private javax.swing.JLabel imagneinicio33;
    private javax.swing.JLabel imagneinicio34;
    private javax.swing.JLabel imagneinicio35;
    private javax.swing.JLabel imagneinicio36;
    private javax.swing.JLabel imagneinicio37;
    private javax.swing.JLabel imagneinicio38;
    private javax.swing.JLabel imagneinicio39;
    private javax.swing.JLabel imagneinicio4;
    private javax.swing.JLabel imagneinicio40;
    private javax.swing.JLabel imagneinicio41;
    private javax.swing.JLabel imagneinicio42;
    private javax.swing.JLabel imagneinicio43;
    private javax.swing.JLabel imagneinicio44;
    private javax.swing.JLabel imagneinicio45;
    private javax.swing.JLabel imagneinicio46;
    private javax.swing.JLabel imagneinicio47;
    private javax.swing.JLabel imagneinicio48;
    private javax.swing.JLabel imagneinicio49;
    private javax.swing.JLabel imagneinicio5;
    private javax.swing.JLabel imagneinicio50;
    private javax.swing.JLabel imagneinicio51;
    private javax.swing.JLabel imagneinicio52;
    private javax.swing.JLabel imagneinicio53;
    private javax.swing.JLabel imagneinicio54;
    private javax.swing.JLabel imagneinicio55;
    private javax.swing.JLabel imagneinicio56;
    private javax.swing.JLabel imagneinicio57;
    private javax.swing.JLabel imagneinicio58;
    private javax.swing.JLabel imagneinicio59;
    private javax.swing.JLabel imagneinicio6;
    private javax.swing.JLabel imagneinicio60;
    private javax.swing.JLabel imagneinicio61;
    private javax.swing.JLabel imagneinicio62;
    private javax.swing.JLabel imagneinicio63;
    private javax.swing.JLabel imagneinicio64;
    private javax.swing.JLabel imagneinicio65;
    private javax.swing.JLabel imagneinicio66;
    private javax.swing.JLabel imagneinicio67;
    private javax.swing.JLabel imagneinicio68;
    private javax.swing.JLabel imagneinicio69;
    private javax.swing.JLabel imagneinicio7;
    private javax.swing.JLabel imagneinicio70;
    private javax.swing.JLabel imagneinicio71;
    private javax.swing.JLabel imagneinicio72;
    private javax.swing.JLabel imagneinicio73;
    private javax.swing.JLabel imagneinicio74;
    private javax.swing.JLabel imagneinicio75;
    private javax.swing.JLabel imagneinicio76;
    private javax.swing.JLabel imagneinicio77;
    private javax.swing.JLabel imagneinicio78;
    private javax.swing.JLabel imagneinicio79;
    private javax.swing.JLabel imagneinicio8;
    private javax.swing.JLabel imagneinicio80;
    private javax.swing.JLabel imagneinicio81;
    private javax.swing.JLabel imagneinicio9;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel224;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel227;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel232;
    private javax.swing.JLabel jLabel233;
    private javax.swing.JLabel jLabel234;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel246;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel255;
    private javax.swing.JLabel jLabel256;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel260;
    private javax.swing.JLabel jLabel261;
    private javax.swing.JLabel jLabel262;
    private javax.swing.JLabel jLabel263;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel266;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel271;
    private javax.swing.JLabel jLabel272;
    private javax.swing.JLabel jLabel273;
    private javax.swing.JLabel jLabel274;
    private javax.swing.JLabel jLabel275;
    private javax.swing.JLabel jLabel276;
    private javax.swing.JLabel jLabel277;
    private javax.swing.JLabel jLabel278;
    private javax.swing.JLabel jLabel279;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel280;
    private javax.swing.JLabel jLabel281;
    private javax.swing.JLabel jLabel282;
    private javax.swing.JLabel jLabel283;
    private javax.swing.JLabel jLabel284;
    private javax.swing.JLabel jLabel285;
    private javax.swing.JLabel jLabel286;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel288;
    private javax.swing.JLabel jLabel289;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel290;
    private javax.swing.JLabel jLabel291;
    private javax.swing.JLabel jLabel292;
    private javax.swing.JLabel jLabel293;
    private javax.swing.JLabel jLabel294;
    private javax.swing.JLabel jLabel295;
    private javax.swing.JLabel jLabel296;
    private javax.swing.JLabel jLabel297;
    private javax.swing.JLabel jLabel298;
    private javax.swing.JLabel jLabel299;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel300;
    private javax.swing.JLabel jLabel301;
    private javax.swing.JLabel jLabel302;
    private javax.swing.JLabel jLabel303;
    private javax.swing.JLabel jLabel304;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel308;
    private javax.swing.JLabel jLabel309;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel310;
    private javax.swing.JLabel jLabel311;
    private javax.swing.JLabel jLabel312;
    private javax.swing.JLabel jLabel313;
    private javax.swing.JLabel jLabel314;
    private javax.swing.JLabel jLabel315;
    private javax.swing.JLabel jLabel316;
    private javax.swing.JLabel jLabel317;
    private javax.swing.JLabel jLabel318;
    private javax.swing.JLabel jLabel319;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel320;
    private javax.swing.JLabel jLabel321;
    private javax.swing.JLabel jLabel322;
    private javax.swing.JLabel jLabel323;
    private javax.swing.JLabel jLabel324;
    private javax.swing.JLabel jLabel325;
    private javax.swing.JLabel jLabel326;
    private javax.swing.JLabel jLabel327;
    private javax.swing.JLabel jLabel328;
    private javax.swing.JLabel jLabel329;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel330;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
